<?php
header("Content-type: text/html; charset=utf-8");
include_once("../classTramite.php");
echo "Criando um objeto novo... <br />";
$tramite = new Tramite();
$tramite->origem = "CPC";
$tramite->destino = "Fundação Araucária";
$tramite->documento = 1;
$tramite->dataTramite = date("Y-m-d");
$tramite->salvar();
echo "Novo objeto salvo... <br />";
echo "Imprimindo objeto... <br />";
echo "<pre>";
print_r($tramite);
echo "</pre>";
echo "Objeto impresso...<hr />";
echo "Localizando objeto...<br />";
$tramite->localizar($tramite->id);
echo "Objeto localizado...<br />";
echo "Imprimindo objeto...<br />";
echo "<pre>";
print_r($tramite);
echo "</pre>";
echo "Objeto impresso...<hr />";
echo "Atualizando objeto... <br />";
$tramite->destino = "SETI";
$tramite->atualizar();
echo "Objeto atualizado... <br />";
echo "Imprimindo objeto...<br />";
echo "<pre>";
print_r($tramite);
echo "</pre>";
echo "Objeto impresso...<hr />";
echo "Deletando objeto...<br />";
$tramite->deletar();
echo "Objeto deletado...<br />";
echo "Imprimindo objeto... <br />";
//$tramite->localizar($tramite->id);
echo "<pre>";
print_r($tramite);
echo "</pre>";
echo "Objeto impresso...<hr />";
echo "Listando objetos... <br />";
$tramites = $tramite->listar();
echo "<pre>";
print_r($tramites);
echo "</pre>";
echo "Objetos impressos...<hr />";
echo "Listando objetos por documento... <br />";
$tramites = $tramite->listarPor("documento",1);
echo "<pre>";
print_r($tramites);
echo "</pre>";
echo "Objetos impressos...<hr />";
echo "Localizando tramites por documento... <br />";
$id = 25; 
$tramites = new Tramite();
$tramites = $tramites->listarPor("documento",$id);
echo "Tramites localizados... <br />";
echo "Listando tramites... <br />";
echo json_encode($tramites);      
echo "<br /> Tramites listados...<hr />";
?>