<?php
header("Content-type: text/html; charset=utf-8");
include_once("../classDocumento.php");
$documento = new Documento();
$documento->titulo = "Ofício nº 035/2016 - ASP/CPC";
$documento->tipoDocumento = 3;
$documento->dataCadastro = date("Y-m-d");
echo $documento->dataCadastro;
echo "<br>Testando conversão de datas: formatarDataDe()<br>";
$documento->formatarDataDe();
echo $documento->dataCadastro;
echo "<br>Testando conversão de datas: formatarDataPara()<br>";
$documento->formatarDataPara();
echo $documento->dataCadastro;
$documento->salvar();
echo "<pre>";
print_r($documento);
echo "</pre>";
$documento->localizar($documento->id);
echo "<pre>";
print_r($documento);
echo "</pre>";
$documento->titulo = "Outro título de documento";
$documento->atualizar();
echo "<pre>";
print_r($documento);
echo "</pre>";
$documento->deletar();
//$documento->localizar($documento->id);
echo "<pre>";
print_r($documento);
echo "</pre>";
$documentos = $documento->listar();
echo "<pre>";
print_r($documentos);
echo "</pre> <hr />";

$documento = new Documento();
$documento->id =  29;
$documento->titulo = "Ble ble";
$documento->tipoDocumento = 4;
$documento->dataCadastro = '30-11-2017';
$documento->qtdTramites =  3;
$documento->atualizar(); 
?>